<?php

namespace Proxies\__CG__\Admin\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paciente extends \Admin\AdminBundle\Entity\Paciente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'nombre', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'apellido', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'edad', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'fechaNac', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'direccion', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'seguroSocial', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'formaActual', 'medicoPref', 'telefonos', 'contactoEmerg');
        }

        return array('__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'nombre', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'apellido', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'edad', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'fechaNac', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'direccion', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'seguroSocial', '' . "\0" . 'Admin\\AdminBundle\\Entity\\Paciente' . "\0" . 'formaActual', 'medicoPref', 'telefonos', 'contactoEmerg');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paciente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', array($apellido));

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', array());

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', array($edad));

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', array());

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNac($fechaNac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNac', array($fechaNac));

        return parent::setFechaNac($fechaNac);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNac', array());

        return parent::getFechaNac();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeguroSocial($seguroSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeguroSocial', array($seguroSocial));

        return parent::setSeguroSocial($seguroSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeguroSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeguroSocial', array());

        return parent::getSeguroSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormaActual($formaActual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormaActual', array($formaActual));

        return parent::setFormaActual($formaActual);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormaActual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormaActual', array());

        return parent::getFormaActual();
    }

    /**
     * {@inheritDoc}
     */
    public function addTelefono(\Admin\AdminBundle\Entity\Telefono $telefonos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTelefono', array($telefonos));

        return parent::addTelefono($telefonos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTelefono(\Admin\AdminBundle\Entity\Telefono $telefonos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTelefono', array($telefonos));

        return parent::removeTelefono($telefonos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonos', array());

        return parent::getTelefonos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonos($telefonos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonos', array($telefonos));

        return parent::setTelefonos($telefonos);
    }

    /**
     * {@inheritDoc}
     */
    public function addContactoEmerg(\Admin\AdminBundle\Entity\ContEmergencia $contactoEmerg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContactoEmerg', array($contactoEmerg));

        return parent::addContactoEmerg($contactoEmerg);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContactoEmerg(\Admin\AdminBundle\Entity\ContEmergencia $contactoEmerg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContactoEmerg', array($contactoEmerg));

        return parent::removeContactoEmerg($contactoEmerg);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoEmerg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoEmerg', array());

        return parent::getContactoEmerg();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoEmerg($ContactoEmerg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoEmerg', array($ContactoEmerg));

        return parent::setContactoEmerg($ContactoEmerg);
    }

    /**
     * {@inheritDoc}
     */
    public function setMedicoPref(\Application\Sonata\UserBundle\Entity\User $medicoPref = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedicoPref', array($medicoPref));

        return parent::setMedicoPref($medicoPref);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicoPref()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicoPref', array());

        return parent::getMedicoPref();
    }

}
